CREATE TABLE forum_posts (
  id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  title VARCHAR(255) NOT NULL COMMENT '帖子标题',
  content TEXT COMMENT '帖子内容（可带 HTML）',
  image_url VARCHAR(500) COMMENT '封面图片 URL',
  like_count INT DEFAULT 0 COMMENT '点赞数',
  comment_count INT DEFAULT 0 COMMENT '评论数',
  created_by VARCHAR(100) NOT NULL COMMENT '创建人邮箱或ID',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
);
